version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongo --eval 'db.runCommand({ ping: 1 })'"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    env_file: .env
    environment:
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
